---
version: "3"
services:
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./https:/app/https-keys
    ports:
      - "80:80"

  auth-service:
    image: artem0matviichuk/in-touch_auth-service:latest
    volumes:
      - ./auth-service-rsa-keys:/app/keys

  blog-service:
    image: artem0matviichuk/in-touch_blog-service:latest
    volumes:
      - ./auth-service-rsa-keys:/app/keys
    restart: on-failure
    
  chat-service:
    image: artem0matviichuk/in-touch_chat-service:latest
    volumes:
      - ./auth-service-rsa-keys:/app/keys
    restart: on-failure
    
  emails-service:
    image: artem0matviichuk/in-touch_emails-service:latest
    volumes:
      - ./auth-service-rsa-keys:/app/keys
    restart: on-failure
      
  rabbitmq:
    image: rabbitmq:3.12.4-management
    ports:
      - 15672:15672
      - 5672:5672

  mssql-auth:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "UPPER_lower_"
      
  mssql-blog:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1434:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "UPPER_lower_"
      
  mssql-chat:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1435:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "UPPER_lower_"

